### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by jescorotero** [dfarache/Tabbed-Container-Extension#29]
Hi
We have detected a significant performance degradation using this extension instead of having the same objects in the same sheet without tabbed-container.

With small apps the performance is similar or you don't realize about it, but when higher ones, if you have three charts one per tab, the performance is very very worst than if you put this three graphs on the sheet without tabbed-container.

For us it was the main handicap for using in production .

Thanks

**Comment by dfarache** [comment]
Hi,
We have also noticed this behavior; in our case, the  low performance happens due to network issues: the extension needs to load several files and won't display until all of them are loaded, so it takes time when the sense server does not respond fast enough. For this reason, we are working on a bundled version of the extension.

It would be interesting to know if the low performance you're experiencing is due to the time it needs to load all the files or if there's really some chunk of code that is lagging the extension.

**Comment by dfarache** [comment]
Closing issue. Can't do much with the information given
