### ISSUE TITLE
Export as csv - pivot dynamic labels don't show in evaluated state

### ISSUE THREAD

**Issue by Purple91** [dfarache/Tabbed-Container-Extension#41]
Hi

Thanks for the tabbed container, it works great! I have 2 pivots in a container with dynamic labels using the "$(=)" method. The display on Qlik Sense is working perfectly.

However, when I export as csv, the label shows up as the full formula instead of showing the evaluated value - is there any way to fix this?

Thanks!

**Comment by dfarache** [comment]
Hello @Purple91 ,

I'll look into it. It should be a quick fix so expect it to be ready next week.

**Comment by Purple91** [comment]
@dfarache Thanks a ton!

**Comment by Purple91** [comment]
@dfarache user just reported that the dimension values don't get exported either..
Original data (on Qlik Sense) looks like this, displaying perfectly:
DimA|DimB|CountX|CountY
----|----|------|------
A1Va|B1Va|23000|10001
A2Va|B2Va|5001|10002

And the export looks like this:
DimA|DimB|$(=(If(ISNull(Type)|CountX|CountX1)))|$(=(If(ISNull(Type)|CountY|CountY1)))
----|----|-------------------|------|----------|-------------------|------|----------
23000|10001
5001|10002

The dimension values are missing and the label shows in the formula form rather than the evaluated version :(

Really looking forward to the fix, I love your extension!!

Thanks a bunch :)

**Comment by dfarache** [comment]
Hi @Purple91 

From what I see, this issue happens because as of now, pivot tables cannot be properly exported with this expression. It's not just the headers; it's the whole export for this type of object.

You may see our progress in the branch we've just opened (https://github.com/dfarache/Tabbed-Container-Extension/tree/issue41-export-pivot). At the moment, it resolves successfully the dynamic measures.

**Comment by dfarache** [comment]
@Purple91 #44 should solve your issue. This fix will give you the value of the dynamic labels for the measures.

Unfortunately, this doesn't work for the dimensions.

Could you try put this pull request and let me know what you think? I'll merge it to master if it solves your issue.

**Comment by Purple91** [comment]
@dfarache Sorry I couldn't download the files from the pull request, is there some way to send them to me for me to try? I had a quick glance at the code though and I think it will work, thanks a ton for the prompt action!!!!

Any thoughts on resolving the issue with the dimension values? For now I'm asking my users to take screenshot, but a fix would be much appreciated!

**Comment by dfarache** [comment]
Sure. My email is displayed on my github profile; we can talk through there and I can send you the code.

The thing is that I tried to set a dynamic label in a dimension of a pivot table and Qlik would interpret it as normal text. However, when I did the same with the columns/measures, Qlik did calculate it as expected. A screenshot would really help me out here!

**Comment by Purple91** [comment]
@dfarache I have emailed you, could you send me the code to try? Thanks!

**Comment by dfarache** [comment]
Sure. Right now I'm in a meeting. I'll be back in 3 hours or so and I'll
send you the files.

**Comment by dfarache** [comment]
Closed by #44

**Comment by dfarache** [comment]
Reopening because the exported data when exporting a pivot table is still not 100% accurate.

Example table to export:
![tabbedcontainer_pivottoexport](https://user-images.githubusercontent.com/5766203/31943811-360580e6-b8ca-11e7-8b08-ad34d99ebebe.JPG)

Exported Excel file:
![tabbedcontainer_pivotexported](https://user-images.githubusercontent.com/5766203/31943836-4b376696-b8ca-11e7-8568-32875b3cbe76.JPG)

**Comment by dfarache** [comment]
Closed by #48
